// <auto-generated />
using System;
using EmployeeCensus.Infastructure.Data.Implementations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmployeeCensus.Infastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeeCensus.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a21f0e7e-500e-4555-9590-c91db20d4ee0"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8122),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8123),
                            Floor = 1,
                            Name = "HR"
                        },
                        new
                        {
                            Id = new Guid("0400eafe-0ef9-4355-9a29-a323cc61949c"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8126),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8126),
                            Floor = 2,
                            Name = "IT"
                        },
                        new
                        {
                            Id = new Guid("b85bcbea-59bc-43ee-841e-6f7f3dcf223e"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8128),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8128),
                            Floor = 3,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = new Guid("c0b5ab59-77f1-43cd-b1fa-1419f597e755"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8211),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8211),
                            Floor = 4,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = new Guid("ddd18d2b-ffdf-4621-b16f-4bd4fcad3110"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8214),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8215),
                            Floor = 5,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = new Guid("9ef0cda4-e5d1-4975-a555-b83f4078dc42"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8216),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8217),
                            Floor = 6,
                            Name = "Support"
                        },
                        new
                        {
                            Id = new Guid("eb55d434-536e-40f4-ab58-558726597975"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8222),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8223),
                            Floor = 7,
                            Name = "R&D"
                        },
                        new
                        {
                            Id = new Guid("a0208518-f27a-4f53-bfa9-a160a2e26608"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8225),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8225),
                            Floor = 8,
                            Name = "Operations"
                        },
                        new
                        {
                            Id = new Guid("24cadc20-3b2a-4e24-a37b-f1f04ad893ac"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8227),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8227),
                            Floor = 9,
                            Name = "Logistics"
                        },
                        new
                        {
                            Id = new Guid("27ba6676-d274-4929-92e7-81ccc23b7e5b"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8229),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8229),
                            Floor = 10,
                            Name = "Legal"
                        });
                });

            modelBuilder.Entity("EmployeeCensus.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30d9fc98-924b-47e8-a38d-f80c7578cd9a"),
                            Age = 30,
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8614),
                            DepartmentId = new Guid("a21f0e7e-500e-4555-9590-c91db20d4ee0"),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8615),
                            FirstName = "John",
                            Gender = 1,
                            IsDeleted = false,
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = new Guid("0b5fc5c8-561c-431c-b4e3-b1b25b56bb94"),
                            Age = 28,
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8617),
                            DepartmentId = new Guid("0400eafe-0ef9-4355-9a29-a323cc61949c"),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8617),
                            FirstName = "Jane",
                            Gender = 2,
                            IsDeleted = false,
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = new Guid("f32b0219-d537-47e9-b0bd-4465ebd8079a"),
                            Age = 35,
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8622),
                            DepartmentId = new Guid("b85bcbea-59bc-43ee-841e-6f7f3dcf223e"),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8622),
                            FirstName = "Mike",
                            Gender = 1,
                            IsDeleted = false,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = new Guid("2ca22dc5-6bc1-4c56-99ec-52873f599a5a"),
                            Age = 32,
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8624),
                            DepartmentId = new Guid("c0b5ab59-77f1-43cd-b1fa-1419f597e755"),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8625),
                            FirstName = "Emily",
                            Gender = 2,
                            IsDeleted = false,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = new Guid("54e012a8-e3fc-40f6-9b68-a2c341c43f11"),
                            Age = 40,
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8627),
                            DepartmentId = new Guid("ddd18d2b-ffdf-4621-b16f-4bd4fcad3110"),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8627),
                            FirstName = "Chris",
                            Gender = 1,
                            IsDeleted = false,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = new Guid("b4324bbc-ce3c-469f-9eb9-c90adf118adc"),
                            Age = 29,
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8629),
                            DepartmentId = new Guid("9ef0cda4-e5d1-4975-a555-b83f4078dc42"),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8629),
                            FirstName = "Anna",
                            Gender = 2,
                            IsDeleted = false,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = new Guid("8867ed9c-470c-47ee-9e64-5c5dd854cd4b"),
                            Age = 45,
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8632),
                            DepartmentId = new Guid("eb55d434-536e-40f4-ab58-558726597975"),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8632),
                            FirstName = "James",
                            Gender = 1,
                            IsDeleted = false,
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = new Guid("4859792f-cf9c-4e0b-b13a-994b8a32b6dd"),
                            Age = 34,
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8634),
                            DepartmentId = new Guid("a0208518-f27a-4f53-bfa9-a160a2e26608"),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8635),
                            FirstName = "Laura",
                            Gender = 2,
                            IsDeleted = false,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = new Guid("60b68e05-6e59-40d5-bbca-fdc03c9d4423"),
                            Age = 50,
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8637),
                            DepartmentId = new Guid("24cadc20-3b2a-4e24-a37b-f1f04ad893ac"),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8637),
                            FirstName = "David",
                            Gender = 1,
                            IsDeleted = false,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = new Guid("8cae1ee4-a4fb-4e9d-a7b9-2f67ad4a9428"),
                            Age = 27,
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8666),
                            DepartmentId = new Guid("27ba6676-d274-4929-92e7-81ccc23b7e5b"),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8666),
                            FirstName = "Sophia",
                            Gender = 2,
                            IsDeleted = false,
                            LastName = "Taylor"
                        });
                });

            modelBuilder.Entity("EmployeeCensus.Domain.Entities.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProgrammingLanguageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProgrammingLanguageId");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c20510c5-33d9-410c-9c63-9772882a9465"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8697),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8698),
                            EmployeeId = new Guid("30d9fc98-924b-47e8-a38d-f80c7578cd9a"),
                            ProgrammingLanguageId = new Guid("6d7920fd-e06d-4b2f-aa82-cd0e941759d4")
                        },
                        new
                        {
                            Id = new Guid("473c220e-d12a-4730-a6ff-51dbce96ca56"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8701),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8701),
                            EmployeeId = new Guid("0b5fc5c8-561c-431c-b4e3-b1b25b56bb94"),
                            ProgrammingLanguageId = new Guid("434faa2f-8af1-49c3-a8e8-c1a17ca25747")
                        },
                        new
                        {
                            Id = new Guid("7cd874d8-947a-4ba5-a75c-10c3fdbf9ed5"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8704),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8704),
                            EmployeeId = new Guid("f32b0219-d537-47e9-b0bd-4465ebd8079a"),
                            ProgrammingLanguageId = new Guid("8caa562d-d065-496c-993c-e55cfb5ff370")
                        },
                        new
                        {
                            Id = new Guid("c0b9ec0b-92f0-49c7-906a-eb824a186c7d"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8706),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8707),
                            EmployeeId = new Guid("2ca22dc5-6bc1-4c56-99ec-52873f599a5a"),
                            ProgrammingLanguageId = new Guid("679c344a-e358-44de-b6b5-67da341e3430")
                        },
                        new
                        {
                            Id = new Guid("daa70592-0683-4546-a2b4-478e726c3a94"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8711),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8712),
                            EmployeeId = new Guid("54e012a8-e3fc-40f6-9b68-a2c341c43f11"),
                            ProgrammingLanguageId = new Guid("5a87939a-87e4-47a9-a8c0-cab80df04da0")
                        },
                        new
                        {
                            Id = new Guid("0a3f7d97-6710-48b5-8351-cffe9d87adcc"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8714),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8714),
                            EmployeeId = new Guid("b4324bbc-ce3c-469f-9eb9-c90adf118adc"),
                            ProgrammingLanguageId = new Guid("15027bab-e1ef-4d1e-8a07-842a25255a4b")
                        },
                        new
                        {
                            Id = new Guid("7c652ff8-a8b2-46cc-934a-a3ae307d2069"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8717),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8717),
                            EmployeeId = new Guid("8867ed9c-470c-47ee-9e64-5c5dd854cd4b"),
                            ProgrammingLanguageId = new Guid("f9b30bdf-b608-4d2f-9749-feb1bd1da6df")
                        },
                        new
                        {
                            Id = new Guid("fad0ae4a-013a-41ce-bd0c-9b8b17a7ad01"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8719),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8720),
                            EmployeeId = new Guid("4859792f-cf9c-4e0b-b13a-994b8a32b6dd"),
                            ProgrammingLanguageId = new Guid("71b8a6cf-93f2-4a0b-82f5-511a95c25180")
                        },
                        new
                        {
                            Id = new Guid("bbe68ab8-3675-4c37-8d21-7897b8960289"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8724),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8724),
                            EmployeeId = new Guid("60b68e05-6e59-40d5-bbca-fdc03c9d4423"),
                            ProgrammingLanguageId = new Guid("457a7ecc-ca5a-4b22-b427-ce175fcc7508")
                        },
                        new
                        {
                            Id = new Guid("e61edaf4-ca6f-4302-ace9-9d7c1c7cb83f"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8726),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8727),
                            EmployeeId = new Guid("8cae1ee4-a4fb-4e9d-a7b9-2f67ad4a9428"),
                            ProgrammingLanguageId = new Guid("a1089b7b-d38e-453d-a9e0-3172dbfcec6d")
                        });
                });

            modelBuilder.Entity("EmployeeCensus.Domain.Entities.ProgrammingLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("ProgrammingLanguages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d7920fd-e06d-4b2f-aa82-cd0e941759d4"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8565),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8565),
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("434faa2f-8af1-49c3-a8e8-c1a17ca25747"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8567),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8568),
                            Name = "Java"
                        },
                        new
                        {
                            Id = new Guid("8caa562d-d065-496c-993c-e55cfb5ff370"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8569),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8570),
                            Name = "Python"
                        },
                        new
                        {
                            Id = new Guid("679c344a-e358-44de-b6b5-67da341e3430"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8572),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8573),
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = new Guid("5a87939a-87e4-47a9-a8c0-cab80df04da0"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8577),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8578),
                            Name = "Ruby"
                        },
                        new
                        {
                            Id = new Guid("15027bab-e1ef-4d1e-8a07-842a25255a4b"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8579),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8580),
                            Name = "Go"
                        },
                        new
                        {
                            Id = new Guid("f9b30bdf-b608-4d2f-9749-feb1bd1da6df"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8582),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8582),
                            Name = "Swift"
                        },
                        new
                        {
                            Id = new Guid("71b8a6cf-93f2-4a0b-82f5-511a95c25180"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8584),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8584),
                            Name = "Kotlin"
                        },
                        new
                        {
                            Id = new Guid("457a7ecc-ca5a-4b22-b427-ce175fcc7508"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8586),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8586),
                            Name = "PHP"
                        },
                        new
                        {
                            Id = new Guid("a1089b7b-d38e-453d-a9e0-3172dbfcec6d"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8588),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8588),
                            Name = "Rust"
                        });
                });

            modelBuilder.Entity("EmployeeCensus.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastActionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8bd2dad-e9c4-4e0e-8a2c-a9450b3367a8"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8750),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8750),
                            LastActionTime = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8749),
                            Password = "password1",
                            Username = "user1"
                        },
                        new
                        {
                            Id = new Guid("14237462-25ec-4e67-ac17-efe0d48d02d0"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8753),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8754),
                            LastActionTime = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8753),
                            Password = "password2",
                            Username = "user2"
                        },
                        new
                        {
                            Id = new Guid("3f1d0083-5613-40da-9160-712095cd75c4"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8759),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8759),
                            LastActionTime = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8758),
                            Password = "password3",
                            Username = "user3"
                        },
                        new
                        {
                            Id = new Guid("bcfcd80a-7026-41ec-b7e1-972031d4c3f9"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8761),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8762),
                            LastActionTime = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8761),
                            Password = "password4",
                            Username = "user4"
                        },
                        new
                        {
                            Id = new Guid("a53b24b1-1f6a-427a-963f-6efafeab24da"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8764),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8765),
                            LastActionTime = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8764),
                            Password = "password5",
                            Username = "user5"
                        },
                        new
                        {
                            Id = new Guid("c61e626d-0511-4399-9a5b-ba37fefac7ad"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8767),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8768),
                            LastActionTime = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8767),
                            Password = "password6",
                            Username = "user6"
                        },
                        new
                        {
                            Id = new Guid("d44897bb-a7e3-47ef-8021-35b5cf2c9e59"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8773),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8773),
                            LastActionTime = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8772),
                            Password = "password7",
                            Username = "user7"
                        },
                        new
                        {
                            Id = new Guid("99077225-2cd4-4711-8466-bbf87c498d94"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8776),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8776),
                            LastActionTime = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8775),
                            Password = "password8",
                            Username = "user8"
                        },
                        new
                        {
                            Id = new Guid("e338cbcb-7910-4d4d-ae86-467d3da07b23"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8778),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8779),
                            LastActionTime = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8778),
                            Password = "password9",
                            Username = "user9"
                        },
                        new
                        {
                            Id = new Guid("f247a176-1c4a-4372-b337-80506f7438ca"),
                            CreatedDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8781),
                            EditDate = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8782),
                            LastActionTime = new DateTime(2024, 7, 4, 12, 50, 58, 38, DateTimeKind.Utc).AddTicks(8781),
                            Password = "password10",
                            Username = "user10"
                        });
                });

            modelBuilder.Entity("EmployeeCensus.Domain.Entities.Employee", b =>
                {
                    b.HasOne("EmployeeCensus.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EmployeeCensus.Domain.Entities.Experience", b =>
                {
                    b.HasOne("EmployeeCensus.Domain.Entities.Employee", "Employee")
                        .WithMany("Experiences")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeCensus.Domain.Entities.ProgrammingLanguage", "ProgrammingLanguage")
                        .WithMany()
                        .HasForeignKey("ProgrammingLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("ProgrammingLanguage");
                });

            modelBuilder.Entity("EmployeeCensus.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Experiences");
                });
#pragma warning restore 612, 618
        }
    }
}
